export const FETCH_DATA_Y = 'FETCH_DATA_Y'
export const FETCH_DATA_X = 'FETCH_DATA_X'
export const FETCH_DATA_RAD = 'FETCH_DATA_RAD'
export const FETCH_DATA_COLOR = 'FETCH_DATA_COLOR'
export const CHANGE_YEAR = 'CHANGE_YEAR'
